name: Cypress run
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github\\workflows\\*"
  pull_request:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      EMAIL_FOR_SIGNUP: ${{ secrets.EMAIL_FOR_SIGNUP }}
      PASSWORD_FOR_SIGNUP: ${{ secrets.PASSWORD_FOR_SIGNUP}}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --force
      - name: Run server and test
        run: npm run cy:run:server
      - name: Create report
        if: always()
        run: npm run report:all
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: mochawesome-report/
